// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/s14t284/simplebank/ent/account"
	"github.com/s14t284/simplebank/ent/predicate"
	"github.com/s14t284/simplebank/ent/transfer"
)

// TransferUpdate is the builder for updating Transfer entities.
type TransferUpdate struct {
	config
	hooks    []Hook
	mutation *TransferMutation
}

// Where appends a list predicates to the TransferUpdate builder.
func (tu *TransferUpdate) Where(ps ...predicate.Transfer) *TransferUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetFromAccountID sets the "from_account_id" field.
func (tu *TransferUpdate) SetFromAccountID(i int) *TransferUpdate {
	tu.mutation.SetFromAccountID(i)
	return tu
}

// SetToAccountID sets the "to_account_id" field.
func (tu *TransferUpdate) SetToAccountID(i int) *TransferUpdate {
	tu.mutation.SetToAccountID(i)
	return tu
}

// SetAmount sets the "amount" field.
func (tu *TransferUpdate) SetAmount(i int) *TransferUpdate {
	tu.mutation.ResetAmount()
	tu.mutation.SetAmount(i)
	return tu
}

// AddAmount adds i to the "amount" field.
func (tu *TransferUpdate) AddAmount(i int) *TransferUpdate {
	tu.mutation.AddAmount(i)
	return tu
}

// SetFromAccountsID sets the "from_accounts" edge to the Account entity by ID.
func (tu *TransferUpdate) SetFromAccountsID(id int) *TransferUpdate {
	tu.mutation.SetFromAccountsID(id)
	return tu
}

// SetFromAccounts sets the "from_accounts" edge to the Account entity.
func (tu *TransferUpdate) SetFromAccounts(a *Account) *TransferUpdate {
	return tu.SetFromAccountsID(a.ID)
}

// SetToAccountsID sets the "to_accounts" edge to the Account entity by ID.
func (tu *TransferUpdate) SetToAccountsID(id int) *TransferUpdate {
	tu.mutation.SetToAccountsID(id)
	return tu
}

// SetToAccounts sets the "to_accounts" edge to the Account entity.
func (tu *TransferUpdate) SetToAccounts(a *Account) *TransferUpdate {
	return tu.SetToAccountsID(a.ID)
}

// Mutation returns the TransferMutation object of the builder.
func (tu *TransferUpdate) Mutation() *TransferMutation {
	return tu.mutation
}

// ClearFromAccounts clears the "from_accounts" edge to the Account entity.
func (tu *TransferUpdate) ClearFromAccounts() *TransferUpdate {
	tu.mutation.ClearFromAccounts()
	return tu
}

// ClearToAccounts clears the "to_accounts" edge to the Account entity.
func (tu *TransferUpdate) ClearToAccounts() *TransferUpdate {
	tu.mutation.ClearToAccounts()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransferUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(tu.hooks) == 0 {
		if err = tu.check(); err != nil {
			return 0, err
		}
		affected, err = tu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransferMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tu.check(); err != nil {
				return 0, err
			}
			tu.mutation = mutation
			affected, err = tu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(tu.hooks) - 1; i >= 0; i-- {
			if tu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransferUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransferUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransferUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TransferUpdate) check() error {
	if _, ok := tu.mutation.FromAccountsID(); tu.mutation.FromAccountsCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Transfer.from_accounts"`)
	}
	if _, ok := tu.mutation.ToAccountsID(); tu.mutation.ToAccountsCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Transfer.to_accounts"`)
	}
	return nil
}

func (tu *TransferUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transfer.Table,
			Columns: transfer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: transfer.FieldID,
			},
		},
	}
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: transfer.FieldAmount,
		})
	}
	if value, ok := tu.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: transfer.FieldAmount,
		})
	}
	if tu.mutation.FromAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfer.FromAccountsTable,
			Columns: []string{transfer.FromAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.FromAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfer.FromAccountsTable,
			Columns: []string{transfer.FromAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.ToAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfer.ToAccountsTable,
			Columns: []string{transfer.ToAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ToAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfer.ToAccountsTable,
			Columns: []string{transfer.ToAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// TransferUpdateOne is the builder for updating a single Transfer entity.
type TransferUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransferMutation
}

// SetFromAccountID sets the "from_account_id" field.
func (tuo *TransferUpdateOne) SetFromAccountID(i int) *TransferUpdateOne {
	tuo.mutation.SetFromAccountID(i)
	return tuo
}

// SetToAccountID sets the "to_account_id" field.
func (tuo *TransferUpdateOne) SetToAccountID(i int) *TransferUpdateOne {
	tuo.mutation.SetToAccountID(i)
	return tuo
}

// SetAmount sets the "amount" field.
func (tuo *TransferUpdateOne) SetAmount(i int) *TransferUpdateOne {
	tuo.mutation.ResetAmount()
	tuo.mutation.SetAmount(i)
	return tuo
}

// AddAmount adds i to the "amount" field.
func (tuo *TransferUpdateOne) AddAmount(i int) *TransferUpdateOne {
	tuo.mutation.AddAmount(i)
	return tuo
}

// SetFromAccountsID sets the "from_accounts" edge to the Account entity by ID.
func (tuo *TransferUpdateOne) SetFromAccountsID(id int) *TransferUpdateOne {
	tuo.mutation.SetFromAccountsID(id)
	return tuo
}

// SetFromAccounts sets the "from_accounts" edge to the Account entity.
func (tuo *TransferUpdateOne) SetFromAccounts(a *Account) *TransferUpdateOne {
	return tuo.SetFromAccountsID(a.ID)
}

// SetToAccountsID sets the "to_accounts" edge to the Account entity by ID.
func (tuo *TransferUpdateOne) SetToAccountsID(id int) *TransferUpdateOne {
	tuo.mutation.SetToAccountsID(id)
	return tuo
}

// SetToAccounts sets the "to_accounts" edge to the Account entity.
func (tuo *TransferUpdateOne) SetToAccounts(a *Account) *TransferUpdateOne {
	return tuo.SetToAccountsID(a.ID)
}

// Mutation returns the TransferMutation object of the builder.
func (tuo *TransferUpdateOne) Mutation() *TransferMutation {
	return tuo.mutation
}

// ClearFromAccounts clears the "from_accounts" edge to the Account entity.
func (tuo *TransferUpdateOne) ClearFromAccounts() *TransferUpdateOne {
	tuo.mutation.ClearFromAccounts()
	return tuo
}

// ClearToAccounts clears the "to_accounts" edge to the Account entity.
func (tuo *TransferUpdateOne) ClearToAccounts() *TransferUpdateOne {
	tuo.mutation.ClearToAccounts()
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransferUpdateOne) Select(field string, fields ...string) *TransferUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transfer entity.
func (tuo *TransferUpdateOne) Save(ctx context.Context) (*Transfer, error) {
	var (
		err  error
		node *Transfer
	)
	if len(tuo.hooks) == 0 {
		if err = tuo.check(); err != nil {
			return nil, err
		}
		node, err = tuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TransferMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tuo.check(); err != nil {
				return nil, err
			}
			tuo.mutation = mutation
			node, err = tuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tuo.hooks) - 1; i >= 0; i-- {
			if tuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransferUpdateOne) SaveX(ctx context.Context) *Transfer {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransferUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransferUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TransferUpdateOne) check() error {
	if _, ok := tuo.mutation.FromAccountsID(); tuo.mutation.FromAccountsCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Transfer.from_accounts"`)
	}
	if _, ok := tuo.mutation.ToAccountsID(); tuo.mutation.ToAccountsCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Transfer.to_accounts"`)
	}
	return nil
}

func (tuo *TransferUpdateOne) sqlSave(ctx context.Context) (_node *Transfer, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   transfer.Table,
			Columns: transfer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: transfer.FieldID,
			},
		},
	}
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transfer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transfer.FieldID)
		for _, f := range fields {
			if !transfer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transfer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Amount(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: transfer.FieldAmount,
		})
	}
	if value, ok := tuo.mutation.AddedAmount(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: transfer.FieldAmount,
		})
	}
	if tuo.mutation.FromAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfer.FromAccountsTable,
			Columns: []string{transfer.FromAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.FromAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfer.FromAccountsTable,
			Columns: []string{transfer.FromAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.ToAccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfer.ToAccountsTable,
			Columns: []string{transfer.ToAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ToAccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   transfer.ToAccountsTable,
			Columns: []string{transfer.ToAccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: account.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Transfer{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transfer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
